name: feel_you
description: A mobile app for deaf-blind people to communicate with the world using only a phone.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  vibration: ^3.1.7
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
